### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Возвращает количество Кубитс, доступных в данный момент для займа.

  Сюда входят неиспользуемые Кубитс; Это относится к Кубитс, возвращенному `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Число Кубитс, которое может быть выделено в `borrowing` инструкции.

      Если используемый целевой компьютер не предоставляет эти сведения, `-1` возвращается.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 99dd2afb66c334b112a2ee511b0437281da6b888
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682408"
