### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Возвращает количество Кубитс, доступных в данный момент для займа. Сюда входят неиспользуемые Кубитс; Это относится к Кубитс, возвращенному `GetQubitsAvailableToUse` .
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Возвращает количество Кубитс, доступных в данный момент для использования.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Эти функции предоставляют сведения о среде, в которой происходит вычисление такта.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 04a3ffe56be7da2c9adc13e2b27fe9ce0f982c44
  ms.sourcegitcommit: 29e0d88a30e4166fa580132124b0eb57e1f0e986
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 10/27/2020
  ms.locfileid: "92713185"
