### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Возвращает количество Кубитс, доступных в данный момент для займа.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Возвращает количество Кубитс, доступных в данный момент для использования.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Эти функции предоставляют сведения о среде, в которой происходит вычисление такта.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201450"
